const API='https://api.p2pquake.net/v2';
const WS='wss://api.p2pquake.net/v2/ws';
const $=id=>document.getElementById(id);
const PREF_NAMES=['北海道','青森県','岩手県','宮城県','秋田県','山形県','福島県','茨城県','栃木県','群馬県','埼玉県','千葉県','東京都','神奈川県','新潟県','富山県','石川県','福井県','山梨県','長野県','岐阜県','静岡県','愛知県','三重県','滋賀県','京都府','大阪府','兵庫県','奈良県','和歌山県','鳥取県','島根県','岡山県','広島県','山口県','徳島県','香川県','愛媛県','高知県','福岡県','佐賀県','長崎県','熊本県','大分県','宮崎県','鹿児島県','沖縄県'];
const INTENSITY={0:'震度0',10:'震度1',20:'震度2',30:'震度3',40:'震度4',45:'震度5弱',46:'震度5弱',50:'震度5強',55:'震度6弱',60:'震度6強',70:'震度7'};
let audioContext=null,soundEnabled=false,soundStyle=localStorage.getItem('eql-sound-style')||'bell',socket=null,retryTimer=null,clockTimer=null,arrivalTimer=null,reportTimer=null;
let historyItems=[],seenIds=new Set(),prefDots=new Map(),reportAt=0,activeWarning=null,lastQuake=null;
function setFeed(state,label){$('feedStatus').dataset.feed=state;$('feedLabel').textContent=label}
function updateClock(){const now=new Date();$('clock').textContent=now.toLocaleTimeString('ja-JP',{timeZone:'Asia/Tokyo',hour12:false})+' JST'}
clockTimer=setInterval(updateClock,1000);updateClock();
function showToast(text){const toast=$('toast');toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
async function enableSound(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC){showToast('このブラウザーは音声に対応していません');return false}try{audioContext??=new AC();if(audioContext.state==='suspended')await audioContext.resume();soundEnabled=true;$('soundToggle').classList.add('on');$('soundToggle').setAttribute('aria-pressed','true');$('soundLabel').textContent='Sound on';return true}catch{showToast('音声を有効にできませんでした');return false}}
function note(freq,start,duration,level=.12,wave='sine',partials=[]){const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type=wave;osc.frequency.setValueAtTime(freq,start);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(level,start+.012);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);osc.connect(gain);gain.connect(audioContext.destination);osc.start(start);osc.stop(start+duration+.03);for(const [ratio,volume] of partials){const overtone=audioContext.createOscillator(),og=audioContext.createGain();overtone.type='sine';overtone.frequency.value=freq*ratio;og.gain.setValueAtTime(.0001,start);og.gain.exponentialRampToValueAtTime(level*volume,start+.008);og.gain.exponentialRampToValueAtTime(.0001,start+duration*.72);overtone.connect(og);og.connect(audioContext.destination);overtone.start(start);overtone.stop(start+duration)}}
function chime(state='detected',preview=false){if(!audioContext||!soundEnabled)return;const now=audioContext.currentTime+.04,urgent=state==='emergency',warning=state==='eew',repeat=urgent?3:warning?2:1;for(let r=0;r<repeat;r++){const offset=r*(urgent ? 0.78 : 0.98),base=now+offset,notes=urgent?[659,784,988]:warning?[784,988]:[784,988];if(soundStyle==='bell'){notes.forEach((f,i)=>note(f,base+i*.17,.75,(urgent ? 0.13 : 0.095), 'sine',[[2.01,.35],[3.92,.12]]))}else if(soundStyle==='glass'){[notes[0],notes[1],notes[0]*1.5].forEach((f,i)=>note(f,base+i*.16,.62,.11,'sine',[[2,.42],[2.76,.11]]))}else{notes.forEach((f,i)=>note(f,base+i*.15,.52,.1,'triangle'));note(notes[0]*.5,base,.82,.045,'sine')}}if(preview)showToast('選択したチャイムを再生しています')}
function setAlertStatus(name){document.body.dataset.state=name;$('statusLabel').textContent=({normal:'Normal',detected:'Detected',eew:'EEW',emergency:'Emergency'})[name]||'Normal';$('alertCard').classList.toggle('alerting',Boolean(activeWarning));$('quakeMarker').classList.toggle('visible',Boolean(lastQuake||activeWarning));$('stateOrb')?.setAttribute('aria-label',name)}
function showQuake(q,announce=false){lastQuake=q;const eq=q.earthquake||{},hyp=eq.hypocenter||{},mag=Number.isFinite(hyp.magnitude)?hyp.magnitude.toFixed(1):'—';$('heroTitle').textContent=hyp.name||'地震を検知しました';$('heroSub').textContent=`地震情報を受信 · M ${mag}`;$('alertEmpty').classList.remove('hidden');$('alertActive').classList.add('hidden');$('mapState').textContent='最新の地震報で観測された震度';setAlertStatus('detected');paintPrefDots(eq.points||[],q.issue?.time||q.time);if(announce){$('heroTitle').textContent='地震を検知しました';$('heroSub').textContent=`${hyp.name||'震源地情報なし'} · M ${mag}`;if(soundEnabled)chime('detected');clearTimeout(reportTimer);reportTimer=setTimeout(()=>{if(!activeWarning)setNormal()},12000)}}
function showWarning(q,announce=false){activeWarning=q;const eq=q.earthquake||{},hyp=eq.hypocenter||{},cancelled=Boolean(q.cancelled);if(cancelled){activeWarning=null;if(lastQuake)showQuake(lastQuake);else setNormal();showToast('緊急地震速報が取り消されました');return}
  const max=Array.isArray(q.areas)?Math.max(-1,...q.areas.map(a=>Number(a.scaleTo??-1))):-1;const emergency=max>=45;$('heroTitle').textContent=emergency?'強い揺れに警戒してください':'緊急地震速報を受信しました';$('heroSub').textContent='安全な場所で身を守ってください';$('alertEmpty').classList.add('hidden');$('alertActive').classList.remove('hidden');$('alertCard').classList.add('alerting');$('alertType').textContent=emergency?'Strong motion warning':'Early warning issued';$('magValue').textContent=Number.isFinite(hyp.magnitude)&&hyp.magnitude>=0?hyp.magnitude.toFixed(1):'—';$('placeValue').textContent=hyp.name||'震源地情報なし';$('depthValue').textContent=Number.isFinite(hyp.depth)&&hyp.depth>=0?`${hyp.depth} km`:'—';$('intensityValue').textContent=INTENSITY[max]||'—';$('intensityValue').dataset.scale=String(max);$('eventTime').textContent=(eq.originTime||'').split(' ')[1]||'—';$('alertStatus').textContent=emergency?'Emergency':'EEW';setAlertStatus(emergency?'emergency':'eew');$('mapState').textContent='緊急地震速報を受信';$('quakeMarker').classList.add('visible');
  const kanagawa=(q.areas||[]).find(a=>String(a.pref||'').includes('神奈川'));if(kanagawa?.arrivalTime){const target=parseJmaTime(kanagawa.arrivalTime);if(target)startArrival(target);else stopArrival()}else stopArrival();if(announce&&soundEnabled)chime(emergency?'emergency':'eew')}
function setNormal(){activeWarning=null;$('heroTitle').textContent='地震活動はありません';$('heroSub').textContent='全国の地震活動を見守っています';$('alertEmpty').classList.remove('hidden');$('alertActive').classList.add('hidden');$('alertCard').classList.remove('alerting');$('alertStatus').textContent='Monitoring';$('mapState').textContent=reportAt?'直近の地震報で観測された震度':'地震報の観測情報を待機中';$('quakeMarker').classList.toggle('visible',Boolean(lastQuake));setAlertStatus('normal');stopArrival()}
function parseJmaTime(value){if(!value)return null;const d=new Date(value.replace(/^(\d{4})\/(\d\d)\/(\d\d)\s+/,'$1-$2-$3T')+'+09:00');return Number.isFinite(d.getTime())?d:null}
function startArrival(target){stopArrival();$('arrivalCountdown').classList.remove('hidden');const paint=()=>{const remain=Math.max(0,Math.ceil((target-Date.now())/1000));$('countdownValue').textContent=`${String(Math.floor(remain/60)).padStart(2,'0')}:${String(remain%60).padStart(2,'0')}`;if(remain===0)stopArrival(false)};paint();arrivalTimer=setInterval(paint,500)}
function stopArrival(hide=true){clearInterval(arrivalTimer);arrivalTimer=null;if(hide)$('arrivalCountdown').classList.add('hidden')}
function renderHistory(){const root=$('timeline');root.innerHTML='';$('historyCount').textContent=String(historyItems.length).padStart(2,'0');$('historyEmpty')?.classList.toggle('hidden',historyItems.length>0);if(!historyItems.length){root.innerHTML='<div class="history-empty">地震情報はまだ届いていません</div>';return}for(const [index,item] of historyItems.slice(0,9).entries()){const row=document.createElement('button');row.className='event-row';row.type='button';row.innerHTML=`<span class="event-line"><i></i></span><span class="event-time"></span><span class="event-main"><b></b><small></small></span><span class="event-chevron">↗</span>`;row.querySelector('.event-time').textContent=item.clock;row.querySelector('.event-main b').textContent=item.place;row.querySelector('.event-main small').textContent=`M ${item.mag}  /  最大震度 ${item.intensity}`;row.addEventListener('click',()=>{document.querySelectorAll('.event-row').forEach(el=>el.classList.toggle('selected',el===row));showQuake(item.source,false);$('heroTitle').textContent=item.place;$('heroSub').textContent=`M ${item.mag}  /  最大震度 ${item.intensity}  /  ${item.clock}`});root.append(row)}}
function addQuake(q,announce=false){const id=q.id||`${q.time}-${q.earthquake?.hypocenter?.name}`;if(seenIds.has(id))return;seenIds.add(id);if(seenIds.size>200)seenIds.delete(seenIds.values().next().value);const eq=q.earthquake||{},hyp=eq.hypocenter||{},raw=eq.maxScale;const item={id,clock:(q.issue?.time||q.time||'').split(' ')[1]?.slice(0,8)||'--:--:--',place:hyp.name||'震源地情報なし',mag:Number.isFinite(hyp.magnitude)?hyp.magnitude.toFixed(1):'—',intensity:INTENSITY[raw]||'—',source:q};historyItems=[item,...historyItems.filter(x=>x.id!==id)].slice(0,24);renderHistory();showQuake(q,announce)}
function intensityClass(scale){if(scale>=45)return'high';if(scale>=30)return'mid';return'low'}
function paintPrefDots(points,time){if(!prefDots.size)return;const latest=new Map();for(const point of points){const name=point.pref;if(!PREF_NAMES.includes(name))continue;const current=latest.get(name);if(!current||Number(point.scale)>current.scale)latest.set(name,{scale:Number(point.scale),addr:point.addr})}const issued=parseJmaTime(time);reportAt=issued?.getTime()||Date.now();const stale=Date.now()-reportAt>10*60*1000;document.body.dataset.reportAge=stale?'stale':'fresh';for(const [name,dot] of prefDots){const data=latest.get(name);const color=data&&!stale?intensityClass(data.scale):'unknown';dot.setAttribute('class',`pref-dot ${color}`);dot.setAttribute('aria-label',data?`${name} ${INTENSITY[data.scale]||'震度情報'}${stale?' · 古い報告':''}`:`${name} 未観測`);dot.setAttribute('title',data?`${name} · ${INTENSITY[data.scale]||'震度情報'} · ${data.addr||''}${stale?' · 10分以上前の報告':''}`:`${name} · 最新報で観測情報なし`)} }
setInterval(()=>{if(!reportAt||Date.now()-reportAt<10*60*1000||document.body.dataset.reportAge==='stale')return;document.body.dataset.reportAge='stale';for(const dot of prefDots.values()){if(!dot.classList.contains('unknown')){dot.setAttribute('class','pref-dot unknown');dot.setAttribute('aria-label',`${dot.getAttribute('aria-label')} · 古い報告`);dot.setAttribute('title',`${dot.getAttribute('title')} · 10分以上前の報告`)}}},30000);
function canonicalPref(name){if(name==='東京')return'東京都';if(name==='大阪')return'大阪府';if(name==='京都')return'京都府';if(name==='北海道'||name.endsWith('県')||name.endsWith('府')||name.endsWith('都'))return name;return`${name}県`}
async function loadMap(){try{const res=await fetch('japan-map.svg');if(!res.ok)throw Error('map');const source=new DOMParser().parseFromString(await res.text(),'image/svg+xml');const svg=document.importNode(source.documentElement,true);svg.classList.add('japan-map');svg.setAttribute('aria-label','日本列島と都道府県の地図');const image=document.querySelector('.japan-map');image.replaceWith(svg);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const overlay=document.createElementNS('http://www.w3.org/2000/svg','g');overlay.setAttribute('class','pref-dot-layer');svg.append(overlay);const inv=svg.getScreenCTM().inverse();for(const group of svg.querySelectorAll('g.prefecture[data-code]')){const title=group.querySelector('title')?.textContent||'',name=canonicalPref(title.split('/')[0].trim()),bbox=group.getBBox(),matrix=group.getScreenCTM();const center=new DOMPoint(bbox.x+bbox.width/2,bbox.y+bbox.height/2).matrixTransform(matrix).matrixTransform(inv);if(!PREF_NAMES.includes(name))continue;const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx',center.x);dot.setAttribute('cy',center.y);dot.setAttribute('r','7');dot.setAttribute('class','pref-dot unknown');dot.setAttribute('aria-label',`${name} 未観測`);dot.setAttribute('tabindex','0');dot.setAttribute('title',`${name} · 最新報で観測情報なし`);overlay.append(dot);prefDots.set(name,dot)}if(lastQuake)paintPrefDots(lastQuake.earthquake?.points||[],lastQuake.issue?.time||lastQuake.time)}catch(error){console.warn('Japan map overlay unavailable',error)}}
function handleMessage(q){if(!q||!q.code||q.test)return;if(q.code===551){addQuake(q,true);return}if(q.code===556){showWarning(q,true);return}if(q.code===554){setFeed('live','Live · EEW signal');return}}
async function loadHistory(){try{const response=await fetch(`${API}/history?codes=551&limit=24`,{cache:'no-store'});if(!response.ok)throw Error('history');const data=await response.json();if(Array.isArray(data)){data.slice().reverse().forEach(q=>addQuake(q,false));historyItems.sort((a,b)=>Date.parse(b.source.issue?.time||b.source.time)-Date.parse(a.source.issue?.time||a.source.time));renderHistory();if(historyItems[0]){const newest=historyItems[0].source;paintPrefDots(newest.earthquake?.points||[],newest.issue?.time||newest.time)}setNormal()}}catch(error){console.warn('Earthquake history unavailable',error);$('historyEmpty').textContent='履歴データを取得できません。接続を確認してください。'}}
function connect(){clearTimeout(retryTimer);setFeed('connecting','Connecting');try{socket=new WebSocket(WS);socket.addEventListener('open',()=>setFeed('live','Live feed'));socket.addEventListener('message',event=>{try{handleMessage(JSON.parse(event.data))}catch{}});socket.addEventListener('error',()=>setFeed('offline','Feed unavailable'));socket.addEventListener('close',()=>{setFeed('retry','Reconnecting');retryTimer=setTimeout(connect,3500)})}catch{setFeed('offline','Feed unavailable');retryTimer=setTimeout(connect,5000)}}
$('soundToggle').addEventListener('click',async()=>{if(soundEnabled){soundEnabled=false;$('soundToggle').classList.remove('on');$('soundToggle').setAttribute('aria-pressed','false');$('soundLabel').textContent='Sound off';showToast('警告音をオフにしました')}else if(await enableSound())showToast('通知音を有効にしました')});
$('testSound').addEventListener('click',async()=>{if(!soundEnabled&&!(await enableSound()))return;chime(activeWarning?(Number($('intensityValue').dataset.scale||0)>=45?'emergency':'eew'):'detected',true)});
document.querySelectorAll('.sound-option').forEach(button=>{button.classList.toggle('active',button.dataset.sound===soundStyle);button.addEventListener('click',async()=>{soundStyle=button.dataset.sound;localStorage.setItem('eql-sound-style',soundStyle);document.querySelectorAll('.sound-option').forEach(item=>item.classList.toggle('active',item===button));if(!soundEnabled&&!(await enableSound()))return;chime('detected',true)})});
loadMap();loadHistory();connect();
